### ISSUE TITLE
Moonlight works flawless over ethernet, but cannot connect over WiFi

### ISSUE THREAD

**Issue by Ostekages** [moonlight-stream/moonlight-docs#101]
Hi guys.

I'm usually one to troubleshoot myself and investigating, but i seriously cannot wrap my head around this issue.
I have a perfect stream from my PC to my Android TV, but none of my Android devices can connect over WiFi.
Does anyone have any idea or experience, in what could be causing this issue? I can ping my PC fine from the Android phone to the PC, but cannot see the Gamestream host.

Would love some help as i am in love with Moonlight! :-)

Best regards
Marc

**Comment by cgutman** [comment]
Can you describe how you have your network set up? Each switch, hub, router, modem, access point, etc.

**Comment by Ostekages** [comment]
OK so I have a fairly simple setup.
Android TV connected to modem via ethernet. A switch from router to two desktops. 
And the modem that creates the 2.4 and 5GHz WiFi. 
Anyway, I actually dig some more testing since then. I can connect fine if I use my external IP, even without being on WiFi. 
So my problem should actually be solved haha. 

Now just to figure out why it suddenly has black screen but audio and inputs works fine. 
I had set up moonlight Tuesday and it worked great with 1080p60fps with 25000 nitrate. Now I cannot even get it to work with 720p30fps 2000-10000 nitrate. Doesn't seem to matter what settings I use. 

No trouble if no solution. I will keep an eye on Moonlight and use Remote meanwhile. Maybe an update will fix my issues :)

**Comment by Ostekages** [comment]
Oops.typo.
A switch between modem and two desktops
