### ISSUE TITLE
can't connect moonlight chrome in internal network

### ISSUE THREAD

**Issue by ghost** [moonlight-stream/moonlight-docs#102]
GFE version : 3.13.1.30
moonlight chrome 0.9.0
Windows 10 pro 16299.309
new surface pro

i cannot connect moonlight chrome in internal network. 
i turn off my firewall and i check my http server works well in this network
is there any setting that i have to do?

**Comment by cgutman** [comment]
Do you have an Android or iOS device that you could try Moonlight on to see if this is specific to your Surface Pro?
