### ISSUE TITLE
Moonlight can't find PC!

### ISSUE THREAD

**Issue by Gaborowaty** [moonlight-stream/moonlight-docs#103]
Hi there!

I have a little issue, so, Moonlight don't see my PC ;/
I am connected to same network, phone is connected using WIFI, and computer is connected using ethernet cable.
I have Windows 7 :/
But Moonlight see my brother's computer which is too connected by ethernet cable.

Any ideas?

**Comment by cgutman** [comment]
What GPU and GeForce Experience version are you running on your PC? Have you enabled GameStream in GeForce Experience?

**Comment by Gaborowaty** [comment]
GPU: Intel Core i5-4460 3.20GHz
GFE Version: 3.13.1.30
Yes, i have.

**Comment by cgutman** [comment]
You don't have an NVIDIA GPU in that machine?

**Comment by Gaborowaty** [comment]
Sorry, I was wrong.
I have Nvidia Geforce GTX 960
