### ISSUE TITLE
Moonlight doesn't stream outside of host's wifi

### ISSUE THREAD

**Issue by mandogy** [moonlight-stream/moonlight-docs#104]
I paired my laptop to the desktop at home, (on the same network), but when I take it outside of my home network I just get a red outline around the my home PC.

**Comment by Jorys-Paulin** [comment]
@mandogy https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#streaming-over-the-internet

**Comment by mandogy** [comment]
I already have all the ports listed on forwarding and I've tested them, I can connect to my IPV4 from Home, but no where else.

**Comment by Jorys-Paulin** [comment]
@mandogy You need to put your Public IP inside the address box then.

**Comment by mandogy** [comment]
I already did that as well. Still red death outline.

**Comment by Jorys-Paulin** [comment]
@mandogy That means you didn't configure your gateway properly, what else can it be?

**Comment by Filip-I** [comment]
Is there a step by step video explaining how to do this, since it is quite confusing for someone who's never done port forwarding?

**Comment by Jorys-Paulin** [comment]
@Filip-I Look up for "Port forwarding" on Google with your router name.

**Comment by mandogy** [comment]
Forgot about this, got it to work on two different networks so far, one network it still says offline.

**Comment by Jorys-Paulin** [comment]
@mandogy So, is the issue resolved?
