### ISSUE TITLE
Moonlight wont connect to my PC don't know what to do 

### ISSUE THREAD

**Issue by knitkap** [moonlight-stream/moonlight-docs#109]
I'm trying to stream games to my phone however when I enter my IP address into the app (I'm using IOS) it says" Ensure game stream is enabled in Geforce experience" which it is. I'd greatly appreciate it if I could get some help

**Comment by Jorys-Paulin** [comment]
@knitkap Have you opened all ports? Could you give us a screenshot of the config, to ensure you got them all?
