### ISSUE TITLE
GeForce experience 3.1.0.52 doesn't work

### ISSUE THREAD

**Issue by mcj201** [moonlight-stream/moonlight-docs#11]
Error: host is offline
Tested on raspi and android

Nvidia's changelog: improved local connectivity and stability for gamestream

**Comment by cgutman** [comment]
Is GameStream turned on in GeForce Experience?

**Comment by mcj201** [comment]
They removed the shield tab, so there is no option to turn it on. 
Downgrade of gfe worked, until it detected the update again

**Comment by cgutman** [comment]
The Shield tab wasn't removed. It's a GFE bug when it goes missing. https://forums.geforce.com/default/topic/964669/gamestream/no-shield-tab-in-the-options-and-no-streaming/

**Comment by mcj201** [comment]
so how can i fix it without owning the shield?

**Comment by cgutman** [comment]
You may try uninstalling and reinstall the latest GFE. If that doesn't work, you can try in GFE settings to check "Allow experimental features", wait 5 minutes or so, then restart GFE and you should get an update to GFE 3.2.
