### ISSUE TITLE
Was there anyway to allow GameStream running on a different session?

### ISSUE THREAD

**Issue by stevefan1999-personal** [moonlight-stream/moonlight-docs#121]
So the basic idea is that I wanted to use my main PC while I launch a game on my iPhone.

I have already patched Terminal Service to allow multiple users using [RDPWrapper](https://github.com/stascorp/rdpwrap), but when I open up Geforce Experience tab in my remote session and go look for SHIELD, it simply said "Information not available!" while I can still view it in my main account on my PC screen. If my main PC logs on to my "Game" account, I can also view it too.

I know GS streams desktop and mouse movement directly, so it might implies that GS only supports console session? Trouble is, I even had console/admin session option turned on in my remote session. So what determines if the SHIELD option is not available otherwise?

**Comment by stevefan1999** [comment]
OK, so what I tried to do is called "multiseating". Is it impossible to do multiseating with GameStream?
