### ISSUE TITLE
Blank Screen with adio

### ISSUE THREAD

**Issue by JUSTs79** [moonlight-stream/moonlight-docs#129]
after 0.3.0 version start to experiencing the problem. trying to connect from win10  i have blank screen with audio, but when i try to connect from android 6 in same time, everything works fine. 
sometimes 0.3.0 have this issue too but occasionally

**Comment by cgutman** [comment]
Please file an issue on the page for the Moonlight client you're using. 

If you're using the new PC client, that's https://github.com/moonlight-stream/moonlight-qt
