### ISSUE TITLE
Moonlight Windows Client - White Screen and Client Crash on FullScreen Display Mode.

### ISSUE THREAD

**Issue by xatornet** [moonlight-stream/moonlight-docs#132]
Using Last Moonlight Client for Windows 10 x64 paired with a PC using GFE version 3.15.0.164 gets me a white screen and then a crash on the client app. Here's the result and the settings used:

**WhiteScreen and Crash:**
[https://imgur.com/zdHrypT](url)

**Settings used:**
[https://imgur.com/yfKIvfd](url)

If I use on client DisplayMode Windows Borderless or Windows mode, it works properly and without any crash.

**Both Client and Server are running:** 
Windows 10 Pro x64 Build 1809
Nvidia Drivers 416.16 with GFE 3.15.0.164
Moonlight PC ver 6.0.0 beta 3 (windows x64 edition)

**Comment by cgutman** [comment]
This issue tracker is for bugs in the documentation. Can you file this issue on the Moonlight PC client issue tracker? https://github.com/moonlight-stream/moonlight-qt/issues
