### ISSUE TITLE
Stream will not work.

### ISSUE THREAD

**Issue by quentin550** [moonlight-stream/moonlight-docs#15]
I am paired to my friends computer and we had played a game 2-3 weeks ago fully and easily. Today however we are paired and I can start a game but then we encounter issues. I will go through the starting game and rtsp handshake, then afterwards I will see a black screen and be pushed out shortly after. This is what happens on my computer. On his computer the game will crash when I get booted or once the game has started up actually but I get "booted out" of the black screen. Often occurring at the same time when I get booted out and the game crashes, his resolution will go down from its native resolution across his entire computer. We are unsure of how to fix it. We've tried restarting our computers, reinstalling moonlight, and repairing.

**Comment by cgutman** [comment]
What version of Moonlight are you using?

**Comment by quentin550** [comment]
The latest chrome version.

**Comment by cgutman** [comment]
V0.6.2? That version fixed the black screen issue with GFE 3.2

**Comment by quentin550** [comment]
Yes 0.6.2. I don't know. I'm not sure what's wrong, as I said, simply 2-3 weeks ago we played through a game together just fine with Moonlight.

**Comment by quentin550** [comment]
I know I installed a small update today for Geforce Experience, it is possible that it could be caused by that?

**Comment by quentin550** [comment]
Now its become that the black screen just stays until Moonlight is closed. I'm not sure what has caused it to change its behavior.

**Comment by cgutman** [comment]
The GeForce Experience update was to 3.2. You need to download the latest version of Moonlight Chrome and upgrade your Moonlight install. 

https://github.com/moonlight-stream/moonlight-chrome/releases

**Comment by quentin550** [comment]
I promise I have installed 0.7.2. twice today. I could take a video of our process and upload it if that would help you?

**Comment by cgutman** [comment]
Sure

**Comment by quentin550** [comment]
Alright I uploaded it here https://youtu.be/7opfm2GhQPk This is what it looks like.

**Comment by cgutman** [comment]
Thanks, can you screenshot the Moonlight entry on your chrome://extensions/ page in Chrome?

**Comment by quentin550** [comment]
Sure thing. 
![23be179d68491500e2ba7adee5364a61](https://cloud.githubusercontent.com/assets/24725301/21446231/78285a54-c891-11e6-829f-761281073f27.png)

**Comment by quentin550** [comment]
Is there a potential fix for our problem?

**Comment by cgutman** [comment]
Hmm, that's pretty strange. I've just been streaming from a PC running GFE 3.2.0.96 with Moonlight Chrome v0.6.2 for about 2 hours without a problem.

You can try the Moonlight Java client - https://github.com/moonlight-stream/moonlight-pc/releases/tag/v0.6.7-r1

The most current Moonlight PC version won't work but the version I linked above will.

**Comment by mt247** [comment]
I have similar problem. Paired nice my laptop to my computer but when I try to open game on moonlight on my lapto it just blinks black screen and goes back to my normal laptop desktop, but it opens steam/games nicely on my pc though. Geforce experience is 3.2.0.96 version and moonlight also latest version.

**Comment by tofof** [comment]
If these are Steam games, it's a steam problem. I noticed that the big picture mode bug has come back (sometime between Dec 10ish and now). 

Complain on Steam forums and until then you can work around it using https://github.com/ianperez/BigPictureWrapper
