### ISSUE TITLE
Could not connect to the host -via internet-

### ISSUE THREAD

**Issue by IBINM** [moonlight-stream/moonlight-docs#29]
Hi guys 
Can someone help with this I have no idea what is the issue here 
![image2](https://cloud.githubusercontent.com/assets/28193420/25555947/ce8e6bb2-2cfb-11e7-8fbb-f0b63945056c.PNG)
![capture](https://cloud.githubusercontent.com/assets/28193420/25555948/ce97d88c-2cfb-11e7-8154-534c86c0a373.PNG)
![image1](https://cloud.githubusercontent.com/assets/28193420/25555949/ce98fbfe-2cfb-11e7-8a35-c9c1414ee12d.PNG)

**Comment by IBINM** [comment]
it only happens when I want to play away from home however locally it works perfect

**Comment by mojics** [comment]
You cannot run the same way when you are out of your home network. 

- Port forward the required ports and access from your static IP if you have one
- Have a VPN at home and you can see your local network 

What I did is the second one, I have setup VPN connection using my ASUS router which has VPN feature (thanks to merlin).
