### ISSUE TITLE
Add additional documentation regarding the Nvidia Tray application

### ISSUE THREAD

**Issue by jmazouri** [moonlight-stream/moonlight-docs#3]
I've been attempting to get Moonlight working recently, and it took me a few hours to get the pairing functioning. For whatever reason, on my machine, it simply would not give me a "Confirm Pairing" prompt, no matter what version combination of Geforce Experience/Moonlight I was running.

The Nvidia Tray application seemed to be the culprit - as it would refuse to launch for me, and didn't appear as an option within the Nvidia Control panel. Googling the issue lead me to a [forum post](https://forums.geforce.com/default/topic/949442/geforce-experience/system-tray-icon-gone/post/4952884/#4952884), with a registry key to remove that ended up allowing me to launch the tray application & get the pair prompt to come up, after which Moonlight worked perfectly across all my devices.

I propose adding this fix to the documentation, wherever you deem fit (the context of my written steps below is underneath step 5 of "Can't pair or stream at all" in the "Troubleshooting" section):

- If you are unable to launch the tray application, perform the following steps:
- Delete the following registry key: `HKEY_LOCAL_MACHINE\SOFTWARE\NVIDIA Corporation\NvTray\ShowInSedona`
- Launch the NVIDIA Control Panel
- Select the "Desktop" menu at the top, and check "Show Notification Tray Icon".

**Comment by cgutman** [comment]
Added this to the documentation.
