### ISSUE TITLE
Connecting people can hear themselves speak over skype/discord

### ISSUE THREAD

**Issue by dawnbomb** [moonlight-stream/moonlight-docs#34]
can't we get a option to mute a SPECIFIC AUDIO SOURCE over moonlight? maybe from the hosts end? so this is NEVER a issue?

constant problem, pretty big design flaw?

**Comment by SpiderManMan** [comment]
This used to not be a problem, it's an issue with the latest GFE. If you revert back to an older version the mouse input lag and audio channel problem will be fixed.

**Comment by Nuuky** [comment]
So what GFE version do we need ? (3.7.0, / 3.6.0 ?)

**Comment by cgutman** [comment]
There's nothing Moonlight can do about this. We don't select which audio sources are streaming to us - we just play whatever pre-mixed audio stream we get.
