### ISSUE TITLE
UWP/Xbox One Support planned?

### ISSUE THREAD

**Issue by 1ne8ight7even** [moonlight-stream/moonlight-docs#4]
Like mentioned in the title. Are there any plans to get moonlight ported to UWP? It would be nice to stream your games from a PC to your Xbox One.

**Comment by DLS-bau** [comment]
In addition it would be great if this could be ported to UWP for PC (and maybe mobile too). Chrome is such a terrible browser, I'm facing Chrome using 60-70% CPU on Windows when streaming 50 Mbps 1080p despite apparently having h264 acceleration enabled.

**Comment by WillPanic** [comment]
I'd be interested in this as well!

**Comment by 1ne8ight7even** [comment]
Any news about that?

**Comment by phayter** [comment]
That would be an awesome feature!
