### ISSUE TITLE
Wacom/Pen Input Support

### ISSUE THREAD

**Issue by howdydewdy** [moonlight-stream/moonlight-docs#42]
Hey All!

Moonlight is incredible! Just found it and really excited by it's usefulness!

Wondering, would it be possible to send pen input through the connection? So say if I was on a Surface or using a Wacom tablet, could my pen input be used on the host machine?

Thanks so much for all your work!

**Comment by mm0zct** [comment]
I would also be very interested in this. For the interest of anyone reading this however, microsoft's own remote desktop software (not the store app, the traditional desktop application that's built into windows) has build in "inking" (I think that's the term they use) support. You can draw quite responsively over remote desktop connections. Unfortunately windows RDP prevents 3d acceleration, so you can't use it with 3d applications - hence the desire for Moonlight support.
