### ISSUE TITLE
Streaming with nvidia p106/p104

### ISSUE THREAD

**Issue by jackyko1991** [moonlight-stream/moonlight-docs#43]
As nvidia just released the high performance CPU without video output, it is commonly refers to deep learning or cryptocurrrency mining.

But the p106 graphic card is just simply 1060 without output port, seems directx and opengl are still remain.

Is it possible to stream game with this card using moonlight?

**Comment by cgutman** [comment]
I have no idea. You'd have to ask NVIDIA about that. I don't have any insider information like that.
