### ISSUE TITLE
Over cellular data works, but wifi network outside home

### ISSUE THREAD

**Issue by Marcoosio** [moonlight-stream/moonlight-docs#44]
I am able to successfully stream over my data, but I cannot get it connected to host computer on outside wifi network. Only over data works

**Comment by Nsteele493** [comment]
Have you tried multiple outside wifi networks? Speed tested them before attempting connection. Also suggest reviewing all your port forwarding

**Comment by cgutman** [comment]
It's likely that your outside WiFi network is blocking Moonlight's ports.
