### ISSUE TITLE
Wake On Lan not Working, Suggestions?

### ISSUE THREAD

**Issue by Nsteele493** [moonlight-stream/moonlight-docs#45]
I have "wake on Lan" enabled in both my bios and device manager settings. Is there anything else I need to be doing to get it setup? Any suggestions? Are there extra port forwards i need to add or are the ones included in the guide already cover this?

**Comment by anderneos** [comment]
Having the same issue. However I'm able to use wake on lan (also via internet) with other apps but not with Moonlight.
Did you test it with some other app just to make sure the issue is with Moonlight?

**Comment by wstlxx** [comment]
I'm having the same problem with moonlight 
but the splashtop works just fine.
I wrote an android app sending several 0xff + MAC address several times,well,it didn't work.
BUT IT SHOULD!!!
 ,I assume there are two different kinds of WOL magic pack?

**Comment by cgutman** [comment]
Can you use Wireshark to capture the WoL packet Splashtop is sending and what Moonlight is sending?

**Comment by wstlxx** [comment]
splashtop sends 7 packets for each waking, 
one WOL(with the info:MagicPacket for BiostarM), one echo(144Request)) one WOL , and 4 TCP packets
not sure what it is. the structure of WOL and echo are the same,TCP are shorter
my app sends only WOL once ,no wonder it doesn't work.
at present i'm not able to test moonlight for some reason,,anyone else?

**Comment by wstlxx** [comment]
![0l r3444lfk1l7 ks94np](https://user-images.githubusercontent.com/35441870/35075324-60d51498-fc2d-11e7-89e7-c495e31ccea2.png)
This is from splashtop: 9 packages including 3 packs sending to 255.255.255.255?

![cg5g5jay3jh1t xc 43hcmt](https://user-images.githubusercontent.com/35441870/35075362-9bf1f9ba-fc2d-11e7-9c48-185d6e2e3ccd.png)
This is from moonlight: 4*5=20 packages

wol packs from both side are almost the same but the 42bytes ahead. seems like ARP.but i'm not sure.
even WOL packages from one side, differs by these 42 bytes too. Usually only 2 bytes of 42 are different.

that's all i have  known so far since i am no expert.. any  idea?  @cgutman

**Comment by wstlxx** [comment]
i finally figured it out ! 
it has nothing to do with the number of same packages sended or the content inside the packages.
it's all about destination.
packs can be sent via unicast or broadcast, obviously, splashtop sends them both, including the destination MAC changed to FF:FF:FF:FF:FF:FF and destination ip changed to 255.255.255.255(so there are 3 WOL packs needed already)
what's more, splashtop packages use specific destination port 9 to WOL and port 7,too, but the port 7 pack will be recognized as an echo pack in wireshark (splashtop also used a 6783 port pack but it is obviously equal to the client port which can be modified in the streamer client so i am sure 6783 is not a key to wake on lan.)
in the android app i wrote , i simply sent all possible packages and it is working . But i cannot change what moonlight is sending.  but i keep wondering if moonlight's WOL function works on some machines?If so i wish someone of the developers could see this and add support for machines like mine.

**Comment by cgutman** [comment]
Yep, you're correct. When the neighbor entry for the PC times out in the client TCP/IP stack, it no longer knows the MAC address to send the packets to because we're targeting the PC's unicast address. We should target the subnet broadcast address instead.
