### ISSUE TITLE
My tablet connections are weird?

### ISSUE THREAD

**Issue by Owerlords** [moonlight-stream/moonlight-docs#46]
After the second latest update my tabled only works with home wifi but not with mobile phone wifi hotspot. BUT the phone works with both its own mobile network and homw wifi?

So tablet works with: wifi only
And phone works with: wifi and own mobile network? 

i dont understand this? hows this possible and whats wrong, after update it wont work on tabled?

EDIT: Moonlight Android v4.8.2 works like it should :) but still would like to keep uptodate (what changed so it would not work on my tabled on never versions?)

**Comment by cgutman** [comment]
Can you try clicking the Add PC button and typing the external IP address of your router? Moonlight may have lost it or it could have changed. You can find that IP address by going to whatsmyip.org on your home network.

**Comment by Owerlords** [comment]
i tried manually adding the computer using my PC network ip adress using google whatsmyip on mobile networks and it says cannot find but home wifi it works. 

My Phone works wifi and its own mobile network

The newest version moonligth onmy tapled does not work with mobile network for some reason? only works on 4.8.2
