### ISSUE TITLE
Moonlight gets stuck after port-forwarding

### ISSUE THREAD

**Issue by Decimate1405** [moonlight-stream/moonlight-docs#48]
I was struggling with port-forwarding a lot and when i finally got through it , there's another problem. When i start Moonlight from another network , it starts but then gets stuck. The cursor wont move and the screen freezes and after a few seconds the app stops and says "Connection Terminated". Please help me with this problem ASAP. 

Thanks!

**Comment by cgutman** [comment]
Can you try reducing the bitrate and resolution in Moonlight to the minimum? It may be an upload bandwidth issue on your PC's Internet connection or a download bandwidth limitation on your client's network.

**Comment by Decimate1405** [comment]
I tried running it on 720p 30FPS and still the same thing
