### ISSUE TITLE
How to game fit whole screen?

### ISSUE THREAD

**Issue by romeomafia** [moonlight-stream/moonlight-docs#5]
I have an iphone 7 regular size not the plus. Running latest moonlight. I have a pc running windows 7. gtx970 sli. Latest nvidia experience version.  

The stream works, but the game stream is showing top right 1/3 of the screen, anyway to fix this..so fit full screen?

Thanks in advance.

**Comment by Popeye1004** [comment]
Hi,
I do have the same issue : gtx 1080, latest geforce experience version and moonlight too (on android).
I tried with the full screen option selected and not, both case only 1/3 of the screen

**Comment by omencat** [comment]
On iPad, aspect ratio is locked to 16:9. No way to stream with 4:3 ratio to fill screen.
