### ISSUE TITLE
TightVNC

### ISSUE THREAD

**Issue by deechoe** [moonlight-stream/moonlight-docs#50]
Having issues connecting through VNC after installing and connecting to the host with Moonlight.

Is there a compatibility issue with VNC?

**Comment by nyakze** [comment]
No issues whatsoever with VNC+Moonlight for me.

**Comment by androbourne** [comment]
I personally use Chrome Remote Desktop Extension. It's good enough for me to remote in and make any changes I need to make to allow Moonlight to function in case something breaks.

Normally i just use remote desktop via Moonlight.
