### ISSUE TITLE
Seemingly random spikes of input lag? Network/bandwidth usage seems normal.

### ISSUE THREAD

**Issue by Dreemlan** [moonlight-stream/moonlight-docs#53]
I was testing out streaming to my friend (I am host) who doesn't live very far away through the internet. When it was capturing my PC's desktop, he had next to no input lag and everything was running smooth (720p 60 FPS, I have 100Mbps download and 6Mbps upload, he has 200 download and 10 upload).

There were random times when it wouldn't run smooth for him, the cursor would kind of slow down as if there were mouse acceleration/smoothing and fine aim wasn't really possible, I figured it would be lag spikes, but when I looked at my router traffic, there weren't really spikes in bandwidth usage and whenever he seemed to lag, my bandwidth was maybe 2Mbps, not even half of my max.

Sometimes the video was also laggy, but for the most part it was input.

(still happens with 30 FPS)

I am connected to my router wirelessly, which may be a factor, so we're going to try him hosting soon because he is wired.

It'd be awesome if I could keep the stream as smooth as when he is just on my desktop/web browser, but when we open a game, it gets a lot worse. Seeing as it is simply recording his device inputs and recording my screen, shouldn't the performance be the same whether he's in a web browser or playing The Witcher 3 or some other program that stresses my PC? My CPU, GPU, and RAM usage is fine.

Thanks! Really impressed with your guys' work, would just like to see if there's anything I could do to improve my experience.

**Comment by anibyl** [comment]
Same here. 100Mbit/s wired network, Steam In-Home streaming works fine (but not with Destiny 2). Ubuntu 16.04 client and Windows 7 host. Unfortunately mouse input is too random and unpredictable.
