### ISSUE TITLE
Internet UDP ports not open and can't connect over the internet

### ISSUE THREAD

**Issue by TheVicBro** [moonlight-stream/moonlight-docs#54]
I have tried port forwarding my ports using a static IP, and have checked if they were open. The TCP seem to be open and fine, but the UDP ports don't appear open which I think is my problem with connecting via internet. I don't know what I did wrong, I forwarded them just like the TCP port except for changing the setting to UDP instead of TCP.

**Comment by cgutman** [comment]
Can you screenshot your router port forwarding configuration?

**Comment by TheVicBro** [comment]
https://gyazo.com/19cb56046325b62aa5ab6f37a5b44524
https://gyazo.com/063942e9ee9453123ae08fa724248541
https://gyazo.com/c51dea540b00db9da414507d08b8f52e
https://gyazo.com/c38ec0ec58285adecefb04e30200737d

**Comment by cgutman** [comment]
That tool probably doesn't correctly detect UDP ports being open (since it's not really possible due to how UDP is designed) and the ports don't open until a stream is actually started. Have you tried actually streaming over the Internet?

**Comment by TheVicBro** [comment]
Yes I have but I don't even find my computer even after inputting my IP
address (not my local one) manually. So therefore I cannot even attempt to
connect to the connection, as I can not find it.

**Comment by enigmacarpc** [comment]
I have a similar issue locally I connect 100% of the time tested remote access and sometimes I connect but get the handshake error or I can't connect at all.

My TCP ports always show open but as @cgutman said UDP can't always be seen and the ports don't show open when not in use.

Seems to be a hit or miss solution remotely.

**Comment by enigmacarpc** [comment]
Hey @TheVicBro I think I found the fix remove your host computer go on to you 4G and of you local network add the host again with the outside IP it will ask you to pair again and now it should work. For some reason adding the host on the LAN first may be causing an issue,

**Comment by TheVicBro** [comment]
Sorry for the late response, I have tried using another WiFi connection
that is not mine, and tried adding the host computer but it still fails

**Comment by TheVicBro** [comment]
nvm, played around a bit and got it to work! thanks a lot!
