### ISSUE TITLE
Previously working but now can't connect/no pairing dialog

### ISSUE THREAD

**Issue by shaun12121** [moonlight-stream/moonlight-docs#56]
A friend and I were able to do some coop through moonlight previously (last session was July 26) but we are now unable to even start the connection.

Over internet, and ports forwarded as per the setup guide. After entering his IP address moonlight fails to connect and the pairing fails.

The only thing that I can think of that changed since then was that GFE updated from 3.7.0.81 to whatever version it is now.

We've gone through the setup guide multiple times and tried everything on the GFE forums as well. Any help is appreciated.

**Comment by cgutman** [comment]
Check that his IP address hasn't changed (some ISPs rotate IP addresses every once in a while). Also check that his PC's internal IP address hasn't changed to not match the port forwarding entries anymore (some routers also rotate these).

**Comment by shaun12121** [comment]
Thanks for the response. We checked it out and it was indeed a change in his internal IP address. After adjusting the port forwarding entries to reflect the change it worked! Quite an embarrassing oversight by our part.
