### ISSUE TITLE
希望能增加全屏裁剪模式，拉伸模式压扁了。

### ISSUE THREAD

**Issue by snakwu** [moonlight-stream/moonlight-docs#57]
我的手机是三星s8+，用拉伸模式，压扁了，希望能增加裁剪模式，谢谢

**Comment by MoonlightSinger** [comment]
我的也是一样，当游戏的分辨率比手机的分辨率小时，会拉伸变形。
Can anyone fix this problem? when your mobile phone resolution is  higher than game resolution ,and their  scale is different from each other, your game displays ugly on moblie phone...

**Comment by qpalzmxdrfyved** [comment]
All the resulotions currentlly supported by moonlight are for 16:9 screens. But there are many devices, such as tablet, which have different aspect ratio, like 4:3, 16:10, 18:9, etc. Is it possible for moonlight to add more resolution options to better support those devices?
