### ISSUE TITLE
Stream only video without handing over controls?

### ISSUE THREAD

**Issue by heavyhdx** [moonlight-stream/moonlight-docs#66]
First of, thank you for this amazing program that makes it easy to stream high quality gameplay to my partner without complicated setup or drawbacks!

However we mainly just want to use this so that they can watch what I'm playing (the delay is too large since they're on the other side of the country).

So is there a simple option I can check that gets rid of their inputs?

Also I want audio on both computers. Is that possible?

Thank you.

**Comment by sippeangelo** [comment]
I just created an feature request for this over at moonlight-chrome: https://github.com/moonlight-stream/moonlight-chrome

Until then you can use my fork of the client, which has disabled all input from working for this exact purpose: https://github.com/sippeangelo/moonlight-chrome-noinput/releases
