### ISSUE TITLE
Wont connect unless I restart pc

### ISSUE THREAD

**Issue by SlayerUSA** [moonlight-stream/moonlight-docs#68]
it will connect to a game, and be perfect, and then suddenly stop and go back to the games screen after like 30 secs with the game still running on moonlight. when I try to connect back to it it get to starting rtsp handshake and then goes back to the games screen. If I click on quit app nothing happens, or when I try to start a different game. So I have to restart my pc thats running the game and then it usually does it all over again

**Comment by cgutman** [comment]
Heh, you're having some seriously bad luck with GFE.

Sounds like the host's streamer is crashing shortly after the stream starts. Can you reproduce the issue, then zip the logs in C:\ProgramData\NVIDIA Corporation\NvStream and link them here?

ProgramData is a hidden folder so you may need to enable hidden files and folders to see it.

**Comment by SlayerUSA** [comment]
I apologize for the wait but I finally got it. It did it again then I restarted my pc so its the old log but just in case heres both of them thank you for your time
[NvStreamerCurrent - Copy.log](https://github.com/moonlight-stream/moonlight-docs/files/1539536/NvStreamerCurrent.-.Copy.log)
[NvStreamerOld.log](https://github.com/moonlight-stream/moonlight-docs/files/1539537/NvStreamerOld.log)
