### ISSUE TITLE
Add firewall rules to troubleshooting guide

### ISSUE THREAD

**Issue by samal84** [moonlight-stream/moonlight-docs#69]
The troubleshooting guide only tells you to disable your whole firewall if you can't connect. It doesn't tell you which specific minimal rules you could add instead.

Might I suggest adding these lines to the troubleshooting guide?

* If you don't want to disable your whole firewall and would like to configure some more specific and minimal firewall rules then try adding these instead:
  * Inbound and outbound allowed for program _C:\Program Files\NVIDIA Corporation\NvContainer\nvcontainer.exe_ on tcp ports 47984, 47989.
  * Inbound and outbound allowed for program _C:\Program Files\NVIDIA Corporation\NvStreamSrv\nvstreamer.exe_ on udp ports 47998, 47999, 48000, and 48010.

**Comment by samal84** [comment]
Also you can add these rules really quick by running these commands in an admin command prompt:

```
netsh advfirewall firewall add rule name="nvcontainer.exe" dir=in profile=private action=allow program="C:\Program Files\NVIDIA Corporation\NvContainer\nvcontainer.exe" protocol=TCP localport=47984,47989 enable=yes
netsh advfirewall firewall add rule name="nvcontainer.exe" dir=out profile=private action=allow program="C:\Program Files\NVIDIA Corporation\NvContainer\nvcontainer.exe" protocol=TCP localport=47984,47989 enable=yes
netsh advfirewall firewall add rule name="nvstreamer.exe" dir=in profile=private action=allow program="C:\Program Files\NVIDIA Corporation\NvStreamSrv\nvstreamer.exe" protocol=UDP localport=47998,47999,48000,48010 enable=yes
netsh advfirewall firewall add rule name="nvstreamer.exe" dir=out profile=private action=allow program="C:\Program Files\NVIDIA Corporation\NvStreamSrv\nvstreamer.exe" protocol=UDP localport=47998,47999,48000,48010 enable=yes
```

**Comment by Juheebus** [comment]
Thank you so much! Please add to the guide.
