### ISSUE TITLE
Moonlight does not support the joystick control of UWP games

### ISSUE THREAD

**Issue by shinobiz** [moonlight-stream/moonlight-docs#70]
I am Chinese, please forgive my English is not very good

I've found a way to support UWP joystick control by streaming

A streaming software from China can simulate the XBOX 360 controller well under the horizon 3, and LT/RT has linear control

But I don't understand the program. The moderator can download it and study it http://www.ihuaj.com/gamecc/

But in addition to the success of simulating XBOX controllers, Compared to the streaming effects of moonlight, it's a piece of shit, and you don't have to care about it

The problem of the controller has been bothering me for a long time! I hope I can help you

**Comment by cgutman** [comment]
Which UWP games are you having issues with? NVIDIA has a similar solution for certain UWP apps.

**Comment by shinobiz** [comment]
I was poor, basically bought steam discount game o(╥﹏╥)o 
UWP only bought the Forza Horizon 3

**Comment by shinobiz** [comment]
by the way. China's streaming software support for the joystick control is really good, in addition to no vibration, steam games and UMP games can be the perfect support, and LT / RT with linear control, I suggest you have time to study it. Sorry, I do not understand computer programming, only to help it
