### ISSUE TITLE
1080p monitor Streaming to a 4k TV

### ISSUE THREAD

**Issue by TranquilThought** [moonlight-stream/moonlight-docs#76]
I can only output 1080p.  Ive tried forcing 4k @30fps& 60fps.  I've tried using nvideas control panel to forced 4k DSR but that didnt help.  How can i run 4k When my monitor is only 1080P?

**Comment by cgutman** [comment]
When GameStream is used on recent GFE, it automatically adds 4K DSR resolution.

Are you using GeForce Experience 3.11?
