### ISSUE TITLE
Connect on dynamic IP

### ISSUE THREAD

**Issue by supadupastar** [moonlight-stream/moonlight-docs#78]
Well, its not really an issue but more like a general question since thats the only place to get in contact. 

How would i go about when i have a dynamic IP on my streaming pc? Do i have to always lookup my ip manually or is there a better way to do that when connecting over the internet? Ive been using another streamer app for some time and there was always a server tray icon that did that whole ip stuff automatically. 

Thanks in advance!

**Comment by cgutman** [comment]
Do you mean the IP address your ISP gives your router is changing (i.e. https://whatsmyip.com changes) or the IP address your router gives your PC (i.e the address in ipconfig on your PC) is changing?

**Comment by supadupastar** [comment]
Thanks for the fast reply! I believe its the IP that the router assigns. I dabbled through the settings and managed the port forwarding, but unsure if i can assign a static adress for the streaming pc.

**Comment by supadupastar** [comment]
I can actually bare the ip thingy, what ive been trying for the last 2 hours was actually starting a game (black desert online) with a gamepad (gamesir g4). When i launch the game in steam bigpicture, it loads very shortly and then drops me back to steam game overview. If i launch via desktop, the gamepad wont work at all and then moonlight crashes. Any idea how i could fix that?
