### ISSUE TITLE
Using gamepad(of streaming device) in mstsc.exe

### ISSUE THREAD

**Issue by inphinio** [moonlight-stream/moonlight-docs#8]
I wanna play Gears of war 4 in Moonlight.
So I have to play with mstsc.exe , but gamepad of streaming device doesn't work.
How could I solve it?

**Comment by tofof** [comment]
Mstsc.exe is Microsoft's remote desktop client and would mean that you're not actually using Moonlight.

Almost certainly though, you got this 'method' from the nvidia forums where people are very confused and think that launching mstsc.exe somehow accomplishes anything other than launching any other desktop application - like calc.exe or notepad.exe.  Yes, you get a gfe/moonlight stream connected to your pc; no, you haven't actually used anything in mstsc (nor calc/notepad) to accomplish it.

**Comment by inphinio** [comment]
@tofof Thx 4 your reply!
