### ISSUE TITLE
Android version mouse support

### ISSUE THREAD

**Issue by shnickelson** [moonlight-stream/moonlight-docs#80]
I have a low end Chromebook and have been trying to get Moonlight working on it.  The Chrome version is mostly unusable, most likely due to my CBs low specs.  The android version runs great.  However, I seem to be having the same peripheral issues as many others.  
I have the two mouse cursors.  One in game, the other from my Chromebook.  The in-game mouse responds to clicks but needs to be dragged by my CB cursor to be moved.  I have seen this as a known issue online but don't see if there is a known fix unless you use the "Rooted Device" version.  Also, some of these posts are on the older side so i'm hoping for a more up-to-date answer.  My Chromebook is not rooted.

**Comment by cgutman** [comment]
The Android app requires Oreo or root to capture the cursor. Until the Chromebook Android runtime is updated to Android Oreo, it won't be able to capture the cursor.
