### ISSUE TITLE
High Mouse "lag"

### ISSUE THREAD

**Issue by V1irus** [moonlight-stream/moonlight-docs#82]
Hey everyone, 
i just got gamesteam running but unfortunately i'm experiencing a kind of "lag" sometimes if i make a move the mouse or Curser just jumps like across the screen. Even a high bitrate cant fix it. Plus getting high inputlag Idk what to do

**Comment by jaydeelive01** [comment]
I agree that this is really annoying. It forbids me to play some strategy games like Stellaris on my computer.

I don't have this issue with Geforce NOW.
It would be very nice if the dev would fix it :-).

**Comment by Kevin135i** [comment]
I been getting this issue since the last couple of updates. Regardless of it being my Laptop or Tablet or Phone... connecting to my Desktop I would often get that weird mouse cursor twitch/jump.
This is why I stopped using moonlight for now. Hopefully they can fix it soon
