### ISSUE TITLE
Screen flickering when streaming from my computer to android TV

### ISSUE THREAD

**Issue by tobbe1113** [moonlight-stream/moonlight-docs#83]
Hello,

I'm having a problem where the screen start flickering on my TV when i'm streaming any game from my computer. It works when streaming from my brother's computer to my TV (which has the same specs) but not from my computer to the TV. It worked before but one day it stopped working and I have tried to update my drivers.

I have a SONY smart TV with moonlight and GTX 960 on both mine and my brother's computer

**Comment by pierrandre** [comment]
I have the flickering as well both on iOS and a Mac using the Chrome plug-in

my TV is off, so the resolution is not properly set.
If I launch a game and set it to full-screen mode: flicker
full screen window or window is fine though

**Comment by tobbe1113** [comment]
I figured it out. It seems like my second monitor was the problem. I deactivated my second monitor and it started working flawlessly again!

If you use two or more monitors try only using one.
