### ISSUE TITLE
firetv "failed to start rtsp handshake" 

### ISSUE THREAD

**Issue by lmontin** [moonlight-stream/moonlight-docs#85]
Hi I have the latest firetv STICK 2017 (with Alexa) and I installed latest moonlight from amazon app store. 
I can connect to my pc with latest nvidia experience and gamestream enabled. all works fine until i try to start a gamestream app I get "failed to start rtsp handshake"

I have tried it on my android phone (redmi 4x) and the gamestream apps load fine .. so it something specific to the firetv stick. 

has anyone had this issue ? how can I help debug ? 

getting moonlight to work on firetv is important as normal casting from windows 10 doesnt work so moonlight is only reasonable / best option (for people with nvidia graphics on pc at least )

**Comment by cgutman** [comment]
Moonlight v5.6.3 just went live on the Amazon app store to address this issue streaming from GeForce Experience 3.12. Check for Moonlight updates on your FireTV and that should fix it.

If you're streaming over the Internet, you'll need to forward a new port: TCP 48010

**Comment by lmontin** [comment]
thanks
i upgraded moonlight version and now it works

great product

cheers
